Sprint_4
Mariyaaaaaaaaaaa/qa_python pull request #2
Opened 2023-11-21 19:26 UTC by Mariyaaaaaaaaaaa

Финальное задание 4 спринта

2023-11-22 22:55 UTC, kadirovgm requested changes

2023-11-22 22:55 UTC, kadirovgm commented on README.md
> +# qa_python
Можно лучше: в readme лучше добавить описание проекта, использованные библиотеки и зависимости, описание тестов

2023-11-22 22:55 UTC, kadirovgm commented on conftest.py
> +    dictionary.add_new_book('Три поросенка')
можно лучше: не легче ли сразу сформировать словарь с книгами?

2023-11-22 22:55 UTC, kadirovgm commented on tests.py
> +    def test_add_new_book_if_name_is_in_book_genre(self):  #1 проверка, что книга которая уже есть в словаре, не добавилась повторно в словарь
можно лучше: комменты о том, что проверяется в тесте - это очень хорошо, но я бы предложил их писать более коротко, например тут, "Книга не может быть добавлена в словарь повторно"

также при описывании методов применяют метод комментирования "докстринг" - советую прочитать про него и воспользоваться им

2023-11-22 22:55 UTC, kadirovgm commented on tests.py
> +    def test_add_new_book_if_name_lenth_more_tnan_40(self):  #2 проверка, что книга с названием больше 40 символов не добавляется в словарь
нужно исправить: давай напишем параметризированный тест, который будет проверять все граничные значения входных данных

параметризация - это когда на вход теста передают тестовые данные из разных классов эквивалентности, при этом зная, что тест вернет одно и то же значение

тест1: передаем книги с длиной названия 0, 41, 42 - книги в словарь не добавлены
тест2: передаем книги с длиной названия 1, 2, 39, 40 - книги в словарь добавлены

2023-11-22 22:55 UTC, kadirovgm commented on tests.py
> +        assert collector.get_book_genre('Пигмалион') == 'Комедии'
отлично!

2023-11-22 22:55 UTC, kadirovgm commented on tests.py
> +        assert collector.get_books_with_specific_genre('Фантастика') == ['Тайная комната']
нужно исправить: давай добавим еще одну книгу в словарь, чтобы убедиться, что метод возвращает книги, жанр которого указан в аргументах функции, а не весь словарь

2023-11-22 22:55 UTC, kadirovgm commented on tests.py
> +        assert len(dictionary.get_books_for_children()) == 2
нужно исправить: лучше не через len() проверять количество книг, а проверять, что вывелись именно детские книги, иначе не совсем корректный тест, который не гарантирует, что эти две книги точно подходят детям

2023-11-22 22:55 UTC, kadirovgm commented on tests.py
> +        assert len(dictionary.get_books_genre()) == 4
можно лучше: спорный тест, выглядит будто ты тестируешь не метод get_books_genre, а функцию питона len()

2023-11-22 22:55 UTC, kadirovgm commented on tests.py
> +        assert len(collector.get_list_of_favorites_books()) == 1
можно лучше: лучше убедиться, что там точно та книга, например, assert book in collector.get_list_of_favorites_books()

2023-11-22 22:55 UTC, kadirovgm commented on tests.py
> +        assert len(collector.get_list_of_favorites_books()) == 0
можно лучше: советую еще также пользоваться assert messages, чтобы более точно описывать ошибку, в случае падения теста

2023-11-22 22:55 UTC, kadirovgm commented on tests.py
> +    @pytest.mark.parametrize('fav_books', favorite_books)
нужно исправить: параметризация тут неверно применена, все книги из одного эквивалентного класса, и по сути ты три раза проводишь один и тот же тест - это не корреткно

лучше убрать отсюда параметризацию и просто првоерить вывод списка избранных через добавление двух книг одновременно, например

2023-11-23 09:21 UTC, Mariyaaaaaaaaaaa commented on README.md
> +# qa_python
Рушат, спасибо за подробные комментарии. Добавила описание, постаралась все учесть.

2023-11-23 09:22 UTC, Mariyaaaaaaaaaaa commented on tests.py
> +    def test_add_new_book_if_name_is_in_book_genre(self):  #1 проверка, что книга которая уже есть в словаре, не добавилась повторно в словарь
Да, спасибо, прочитала, исправила на docstring. Не знала этот момент, буду теперь пользоваться!

2023-11-23 09:23 UTC, Mariyaaaaaaaaaaa commented on tests.py
> +        assert len(dictionary.get_books_for_children()) == 2
Да, у меня была эта заготовка
assert dictionary.get_books_for_children() == ['Лисица и журавль', 'Маша и медведь']
и в последний момент я ее убрала(( , оставила длину. Действительно, длина не гарантирует, что именно те 2 книги, которые подходят детям. Спасибо!

2023-11-23 09:28 UTC, Mariyaaaaaaaaaaa commented on tests.py
> +        assert len(collector.get_list_of_favorites_books()) == 1
Да, точно, исправила, спасибо!

2023-11-23 10:03 UTC, Mariyaaaaaaaaaaa commented on tests.py
> +        assert len(collector.get_list_of_favorites_books()) == 0
Точно, спасибо, добавила!

2023-11-23 10:11 UTC, Mariyaaaaaaaaaaa commented on tests.py
> +    @pytest.mark.parametrize('fav_books', favorite_books)
Да, спасибо, поправила

2023-11-23 10:58 UTC, Mariyaaaaaaaaaaa commented on tests.py
> +    def test_add_new_book_if_name_lenth_more_tnan_40(self):  #2 проверка, что книга с названием больше 40 символов не добавляется в словарь
Сделала!

2023-11-24 07:52 UTC, kadirovgm commented on tests.py
> +    @pytest.mark.parametrize('fav_books', favorite_books)
привет! да, через AND сработает

2023-11-24 08:48 UTC, Mariyaaaaaaaaaaa commented
Commit_after_correction  - Внесены правки по замечаниям

2023-11-24 23:33 UTC, kadirovgm approved these changes

2023-11-24 23:33 UTC, kadirovgm commented on tests.py
> +        """Книга не может быть добавлена в словарь повторно."""
отлично!

2023-11-24 23:33 UTC, kadirovgm commented on tests.py
> +        """Книга не может быть добавлена в словарь повторно."""
отлично!

2023-11-24 23:33 UTC, kadirovgm commented on tests.py
> +    @pytest.mark.parametrize('correct_lenth', books_with_correct_lenth)
супер!

2023-11-25 06:10 UTC, merged